version: '2'
services:
  mariadb:
    image: bitnami/mariadb:latest
    restart: always
    networks:
      - moodlenet
    environment:
#       ALLOW_EMPTY_PASSWORD is recommended only for development.
#     -  ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=pknQxSy3t8j2q4Wm
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=QwgFKnnRD64S2ABx
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: bitnami/moodle:latest
    restart: always
    ports:
      - '80:8080'
      - '443:8443'
    networks:
      - moodlenet
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DATABASE_PASSWORD=QwgFKnnRD64S2ABx
#       ALLOW_EMPTY_PASSWORD is recommended only for development.
#     - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_USERNAME=manager
      - MOODLE_PASSWORD=YeH2sfYZuMhcc2xE
      - MOODLE_EMAIL=soporte@tqcorp.onmicrosoft.com
      - MOODLE_HOST=academy.tqcorp.com
      - MOODLE_SITE_NAME=Team Quality Academy
#     - MOODLE_REVERSEPROXY=true
#     - MOODLE_SSLPROXY=true
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
      - /home/uroot/cert:/certs
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
networks:
  moodlenet:
    driver: bridge