version: "3"
services:
  mysql:
    image: mysql:latest
    command: mysqld --sql_mode=""
    container_name: snipe_mysql
    restart: always
    networks:
      - sitnet
    volumes:
      - /root/data/snipe_mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=EV7ehdGyeSLAtm3W
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=EV7ehdGyeSLAtm3W
      - MYSQL_DATABASE=snipe
  snipeit:
    image: linuxserver/snipe-it:latest
    container_name: snipe-it
    restart: always
    networks:
      - sitnet
    depends_on:
      - mysql
    volumes:
      - /root/data/snipe_it:/config
    environment:
      - APP_KEY=base64:3ilviXqB9u6DX1NRcyWGJ+sjySF+H18CPDGb3+IVwMQ=
      - APP_TIMEZONE=America/Argentina/Buenos_Aires
      - APP_LOCALE=en
      - PHP_UPLOAD_LIMIT=100
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://snipeit.tqcorp.com
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipe
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=EV7ehdGyeSLAtm3W
      - PGID=1000
      - PUID=1000
      - MAIL_ENCRYPTION=null
      - MAIL_DRIVER=smtp
      - MAIL_HOST=postfix.tqcorp.com
      - MAIL_PORT=25
      - MAIL_FROM_ADDR=snipeit@tqcorp.com
      - MAIL_FROM_NAME='Snipe-IT'
      - MAIL_REPLYTO_ADDR=snipeit@tqcorp.com
      - MAIL_REPLYTO_NAME='Snipe-IT'
      - MAIL_AUTO_EMBED_METHOD='attachment'
      - ENABLE_HSTS=true
    ports:
      - "80:80"
      - "443:443"
networks:
  sitnet:
    driver: bridge
