version: '3'

services:
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./cert:/etc/nginx/cert
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443