version: '3.3'
services:
    linkapi:
        volumes:
            - 'C:/Docker/Link/linkapi/dataVolumen:c:/TeamQuality/logs'
        container_name: linkapicont
        ports:
            - '7000:7000'
            - '8000:8000'
        image: linkapi:latest

    linkapiproxy:
        ports:
            - '7001:7001'
            - '8001:8001'
        container_name: linkapiproxycont
        image: linkapiproxy:latest